name: Slack Archive Automation

on:
  workflow_dispatch:
  #schedule:
   # - cron: '*/5 * * * *'

jobs:
  archive-slack:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Node.js をセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 必要な依存関係をインストール
      run: |
        npm install
      working-directory: ./slack-archive 
      
    - name: Expect をインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
      

    - name: Slack アーカイブを実行（全チャンネル）
      run: |
        export SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}
        npx slack-archive download --channel-types public_channel --automatic
  
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

    - name: アーカイブ結果を成果物としてアップロード
      uses: actions/upload-artifact@v3
      with:
        name: slack-archive-results
        path: |
          ./slack-archive/html/**/*
          ./slack-archive/index.html
          ./slack-archive/search.html

    - name: 結果をリモートにプッシュ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # すべての変更されたファイルを追加
        git add .
        
        # コミットメッセージには日付を追加して、変更内容が明確になるように
        git commit -m "Update Slack archive $(date)"
        
        # プッシュ
        git push

