name: Slack Archive Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  archive-slack:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Node.js をセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 必要な依存関係をインストール
      run: |
        npm install
      working-directory: ./slack-archive 
      
    - name: Expect をインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
      

    - name: Slack アーカイブを実行（全チャンネル）
      run: |
        expect -c "
          spawn npx slack-archive
          expect \\\"Please enter your Slack token\\\"
          send \\\"$SLACK_TOKEN\\r\\\"
          expect \\\"Which channel types do you want to download?\\\"
          send \\\" \\\"    # Press space to select Public Channels
          send \\\"\\r\\\"   # Press Enter to confirm channel type selection
          expect \\\"Which channels do you want to download?\\\"
          send \\\"a\\\"    # Press 'a' to select all channels
          send \\\"\\r\\\"   # Press Enter to confirm channel selection
          expect eof
        "
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          
    - name: 結果をリモートにプッシュ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update Slack archive ($(date))"
        git push
