name: Slack Archive Automation

on:
  workflow_dispatch:
  #schedule:
   # - cron: '*/5 * * * *'

jobs:
  archive-slack:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Node.js をセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 必要な依存関係をインストール
      run: |
        npm install
      working-directory: ./slack-archive 
      
    - name: Expect をインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
      

    - name: Slack アーカイブを実行（全チャンネル）
      run: |
        export SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}
        
        expect -d -c "
          spawn npx slack-archive download --channel-types public_channel
    
          # チャンネル選択のプロンプトが出たら、'a'を送信してすべてのチャンネルを選択
          expect -re \".*Which channels do you want to download.*\"
          
          # チャンネル名のリストが表示されるのを待つ
          expect -re \".*◯.*\"  # チャンネル名が表示されるまで待機

          # 全てのチャンネルを選択
          send \"a\"  # 'a'を送信してすべてのチャンネルを選択
          sleep 2
          send \"\r\"  # Enterキーを送信
          sleep 2
        
          # 他の出力には何もしない
          expect eof
        "
        
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          
    - name: 結果をリモートにプッシュ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update Slack archive ($(date))"
        git push
