name: Upload Files to Google Drive

on: [push]

env:
  TARGET_TEX_FILES: "./slack-archive/html ./slack-archive/index.html ./slack-archive/search.html" 
  GOOGLE_DRIVE_DESTINATION: /slack-archive

jobs:
  upload-latex:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v2

    - name: 既存のファイルをアップロード用ディレクトリに移動
      run: |
        mkdir -p upload
        # htmlディレクトリとファイルをそのままコピー
        for TARGET_TEX_FILE in ${{ env.TARGET_TEX_FILES }}; do
          if [ -d $TARGET_TEX_FILE ]; then
            # ディレクトリがあれば、そのままuploadディレクトリにコピー
            cp -r $TARGET_TEX_FILE ./upload/
          elif [ -f $TARGET_TEX_FILE ]; then
            # ファイルがあれば、uploadディレクトリにコピー
            cp $TARGET_TEX_FILE ./upload/
          fi
        done

    - name: Google Driveにアップロード
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        upload-from: ./upload
        upload-to: ${{ env.GOOGLE_DRIVE_DESTINATION }}
